-- Vaildating emails
DROP TRIGGER IF EXISTS VALIDTING_EMAIL;
DELIMITER $$
CREATE TRIGGER VALIDTING_EMAIL BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    IF NEW.email <> OLD.email
    THEN
        SET NEW.valid_email = 0;
    END IF;
END $$
DELIMITER ;
